export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';

export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';

export const UNDELETE_TASK_ERROR = 'UNDELETE_TASK_ERROR';

export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';

export const FILTER_TASKS = 'FILTER_TASKS';
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const UNLOAD_TASKS_SUCCESS = 'UNLOAD_TASKS_SUCCESS';

export const UPDATE_ACCOUNT_CONFIG = 'UPDATE_ACCOUNT_CONFIG';

export const GET_PUBLIC_LIST_SUCCESS = 'GET_PUBLIC_LIST_SUCCESS';
export const GET_PUBLIC_LIST_ERROR = 'GET_PUBLIC_LIST_ERROR';

export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_ERROR = 'UPDATE_ACCOUNT_ERROR';

export const UPDATE_SELECTED_LIST = 'UPDATE_SELECTED_LIST';
export const GET_LIST_BY_ID_SUCCESS = 'GET_LIST_BY_ID_SUCCESS';
